version: '3.8'

services:
  reverse_proxy:
    image: nginx:1.23.1-alpine
    volumes:
      - ./reverse_proxy/default.conf.prod:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - frontend
      - backend
  
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    environment:
      NODE_ENV: 'production'
    logging:
      driver: journald
      options:
        tag: reverse_proxy

volumes:
  node_modules: