version: '3.8'

services:
  frontend:
    build:
      context: src/frontend
      dockerfile: frontend.Dockerfile
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    ports:
      - 9000:9000
    environment:
      PORT: 9000
      WATCHPACK_POLLING: 'true'

volumes:
  node_modules: