version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    ports:
      - 8080:8000
    environment:
      NODE_ENV: 'production'
    logging:
      driver: journald
      options:
        tag: reverse_proxy

volumes:
  node_modules: