version: '3.8'

services:
  reverse_proxy:
    image: nginx:1.23.1-alpine
    volumes:
      - ./reverse_proxy/default.conf.dev:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
  
  frontend:
    build:
      context: src/frontend
      dockerfile: frontend.Dockerfile
    volumes:
      - frontend_node_modules:/app/node_modules
    environment:
      PORT: 3000
      WATCHPACK_POLLING: 'true'

  backend:
    build:
      content: src
      dockerfile: backend.Dockerfile
    volumes:
      - backend_node_modules:/app/node_modules
      - .:/app

volumes:
  frontend_node_modules:
  backend_node_modules: