version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./src/frontend:/app
    ports:
      - 3000:3000
    restart: always
    environment:
      WATCHPACK_POLLING: 'true'
      WDS_SOCKET_HOST: '0.0.0.0'
      WDS_SOCKET_PORT: 443

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - backend_node_modules:/app/node_modules
      - ./src:/app
    ports:
      - 8000:8000
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: true
      NODE_ENV: 'development'

volumes:
  frontend_node_modules:
  backend_node_modules: