version: '3.8'

services:
  reverse_proxy:
    image: nginx:1.23.1-alpine
    volumes:
      - ./reverse_proxy/default.conf.dev:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - frontend
      - backend
  
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./src/frontend:/app
    restart: always
    environment:
      PORT: 3000
      WATCHPACK_POLLING: 'true'

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - backend_node_modules:/app/node_modules
      - ./src:/app
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: true
      NODE_ENV: 'development'
    command: ["pm2-dev", "app.js"]

volumes:
  frontend_node_modules:
  backend_node_modules: